#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.

firstvalue = 1
nextvalue = 2
total = 0
totalevensum = 2
#print(firstvalue)
#print(nextvalue)
while nextvalue <4000000:
    
    for i in range(8):
        total = firstvalue + nextvalue
        firstvalue = nextvalue
        nextvalue = total
        if nextvalue %2 ==0:
            totalevensum = totalevensum+ nextvalue

print (totalevensum)

